=== alphagov/govuk-content-schemas/dist/formats/unpublishing/publisher/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "content_id",
    "format",
    "publishing_app",
    "rendering_app",
    "update_type",
    "locale",
    "routes",
    "public_updated_at"
  ],
  "properties": {
    "base_path": {
      "$ref": "#/definitions/absolute_path"
    },
    "content_id": {
      "$ref": "#/definitions/guid"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "format": {
      "type": "string",
      "enum": [
        "unpublishing"
      ]
    },
    "public_updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "publishing_app": {
      "type": "string"
    },
    "rendering_app": {
      "type": "string"
    },
    "update_type": {
      "enum": [
        "major",
        "minor",
        "republish"
      ]
    },
    "locale": {
      "type": "string"
    },
    "need_ids": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "routes": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/route"
      }
    },
    "redirects": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/route"
      }
    },
    "access_limited": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "users"
      ],
      "properties": {
        "users": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "analytics_identifier": {
      "type": "string"
    },
    "phase": {
      "description": "The service design phase of this content item - https://www.gov.uk/service-manual/phases",
      "type": "string",
      "enum": [
        "alpha",
        "beta",
        "live"
      ]
    },
    "details": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "unpublished_at"
      ],
      "properties": {
        "explanation": {
          "type": [
            "string",
            "null"
          ]
        },
        "unpublished_at": {
          "type": "string",
          "format": "date-time"
        },
        "alternative_url": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        }
      }
    },
    "links": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "can_be_replaced_by"
      ],
      "properties": {
        "can_be_replaced_by": {
          "$ref": "#/definitions/guid_list"
        },
        "mainstream_browse_pages": {
          "description": "Powers the /browse section of the site. These are known as sections in some legacy apps.",
          "$ref": "#/definitions/guid_list"
        },
        "topics": {
          "description": "Powers the /topic section of the site. These are known as specialist sectors in some legacy apps.",
          "$ref": "#/definitions/guid_list"
        },
        "policies": {
          "description": "These are for collecting content related to a particular government policy.",
          "$ref": "#/definitions/guid_list"
        },
        "policy_areas": {
          "description": "A largely deprecated tag currently only used to power email alerts.",
          "$ref": "#/definitions/guid_list"
        }
      }
    }
  },
  "definitions": {
    "absolute_path": {
      "type": "string",
      "pattern": "^/(([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})+(/([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)*)?$",
      "description": "A path only. Query string and/or fragment are not allowed."
    },
    "guid": {
      "type": "string",
      "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
    },
    "guid_list": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/guid"
      }
    },
    "route": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "path",
        "type"
      ],
      "properties": {
        "path": {
          "type": "string"
        },
        "type": {
          "enum": [
            "prefix",
            "exact"
          ]
        }
      }
    }
  }
}

=== alphagov/govuk-content-schemas/formats/unpublishing/publisher/examples/unpublishing_links.json
{
  "content_id": "19ed8498-37ed-4c8e-b0bf-accbb2cf5477",
  "base_path":"/government/case-studies/bubble-trouble",
  "format":"unpublishing",
  "locale":"en",
  "public_updated_at":"2014-04-30T23:01:51.000+00:00",
  "publishing_app": "whitehall",
  "rendering_app": "government-frontend",
  "update_type": "major",
  "routes": [
    {
      "path": "/government/case-studies/bubble-trouble",
      "type": "exact"
    }
  ],
  "links":{
    "can_be_replaced_by": [
      "780026aa-a564-434f-9b37-8d83c0ba3d3b"
    ]
  }
}

=== alphagov/govuk-content-schemas/formats/unpublishing/publisher/examples/unpublishing.json
{
  "content_id": "19ed8498-37ed-4c8e-b0bf-accbb2cf5477",
  "base_path":"/government/case-studies/bubble-trouble",
  "title":"Bubble and trouble",
  "description":"A case study about bubble and trouble.",
  "format":"unpublishing",
  "need_ids":[],
  "locale":"en",
  "public_updated_at":"2014-04-30T23:01:51.000+00:00",
  "publishing_app": "whitehall",
  "rendering_app": "government-frontend",
  "update_type": "major",
  "details":{
    "explanation": "This is now redundant",
    "unpublished_at":"2014-05-01T14:59:17+01:00",
    "alternative_url": null
  },
  "routes": [
    {
      "path": "/government/case-studies/bubble-trouble",
      "type": "exact"
    }
  ]
}
