=== alphagov/govuk-content-schemas/dist/formats/case_study/frontend/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "base_path",
    "format",
    "locale",
    "public_updated_at"
  ],
  "properties": {
    "base_path": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "format": {
      "type": "string",
      "enum": [
        "case_study"
      ]
    },
    "public_updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "locale": {
      "type": "string"
    },
    "need_ids": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "details": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "body",
        "first_public_at"
      ],
      "properties": {
        "body": {
          "type": "string"
        },
        "image": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "url": {
              "type": "string",
              "format": "uri"
            },
            "alt_text": {
              "type": "string"
            },
            "caption": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ]
            }
          }
        },
        "format_display_type": {
          "type": "string",
          "enum": [
            "case_study"
          ]
        },
        "first_public_at": {
          "type": "string",
          "format": "date-time"
        },
        "change_history": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "public_timestamp": {
                "type": "string",
                "format": "date-time"
              },
              "note": {
                "type": "string"
              }
            },
            "required": [
              "public_timestamp",
              "note"
            ]
          }
        },
        "tags": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "browse_pages": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "topics": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "policies": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "withdrawn_notice": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "explanation": {
              "type": "string"
            },
            "withdrawn_at": {
              "format": "date-time"
            }
          }
        },
        "archive_notice": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "explanation": {
              "type": "string"
            },
            "archived_at": {
              "format": "date-time"
            }
          }
        }
      }
    },
    "links": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "lead_organisations"
      ],
      "properties": {
        "lead_organisations": {
          "$ref": "#/definitions/frontend_links"
        },
        "related_policies": {
          "$ref": "#/definitions/frontend_links"
        },
        "supporting_organisations": {
          "$ref": "#/definitions/frontend_links"
        },
        "world_locations": {
          "$ref": "#/definitions/frontend_links"
        },
        "worldwide_organisations": {
          "$ref": "#/definitions/frontend_links"
        },
        "worldwide_priorities": {
          "$ref": "#/definitions/frontend_links"
        },
        "document_collections": {
          "$ref": "#/definitions/frontend_links"
        },
        "available_translations": {
          "$ref": "#/definitions/frontend_links"
        }
      }
    },
    "updated_at": {
      "type": "string",
      "format": "date-time"
    }
  },
  "definitions": {
    "route": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "path",
        "type"
      ],
      "properties": {
        "path": {
          "type": "string"
        },
        "type": {
          "enum": [
            "prefix",
            "exact"
          ]
        }
      }
    },
    "guid_list": {
      "type": "array",
      "items": {
        "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
      }
    },
    "frontend_links": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "title",
          "base_path",
          "locale"
        ],
        "properties": {
          "title": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "base_path": {
            "type": "string"
          },
          "api_url": {
            "type": "string",
            "format": "uri"
          },
          "web_url": {
            "type": "string",
            "format": "uri"
          },
          "locale": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== alphagov/govuk-content-schemas/formats/case_study/frontend/examples/translated.json
{
    "base_path": "/government/case-studies/doing-business-in-spain.es",
    "description": "Los negocios y las inversiones de las empresas espa\u00f1olas en el exterior tienen \u00e9xito y, al mismo tiempo, empresas extranjeras siguen identificando atractivas oportunidades de negocio que ofrece Espa\u00f1a.",
    "details": {
        "body": "<div class=\"govspeak\"><p>Los equipos de  UK Trade &amp; Investment (Departamento gubernamental brit\u00e1nico de negocios e inversiones) de Madrid, Barcelona y Bilbao, contribuyen a que el n\u00famero de empresas brit\u00e1nicas que hacen negocios en Espa\u00f1a sea cada vez mayor; as\u00ed como a impulsar la inversi\u00f3n espa\u00f1ola en el Reino Unido.</p>\n\n<p>Martin Phelan, director de UKTI Iberia, explica con m\u00e1s detalle que ofrece Espa\u00f1a a la empresa brit\u00e1nica.</p>\n\n<p><a rel=\"external\" href=\"http://www.youtube.com/watch?v=C-O59O0_DOY&amp;list=UUWl6ZVke4P2GYpk6eq4BPIQ&amp;index=21\">Martin Phelan</a></p>\n\n<p>London School of Economics y la empresa brit\u00e1nica Tunstall hablan de su experiencia en el mercado espa\u00f1ol y c\u00f3mo UKTI ha contribuido a su \u00e9xito.</p>\n\n<p><a rel=\"external\" href=\"http://www.youtube.com/watch?v=reDxB4wpi2o&amp;list=UUWl6ZVke4P2GYpk6eq4BPIQ&amp;index=23\">Adam Austerfield</a></p>\n\n<p><a rel=\"external\" href=\"http://www.youtube.com/watch?v=WSo0LJ_c1-I\">Joe Killen</a></p>\n\n<p>A pesar de la actual situaci\u00f3n econ\u00f3mica en Espa\u00f1a, existe una gran actividad empresarial internacional y nacional. El pa\u00eds es la cuarta mayor econom\u00eda de la zona del euro y la 13 a nivel mundial. Espa\u00f1a ha mantenido el crecimiento de sus exportaciones, que aumentaron un 18% entre 2010 y 2012.</p>\n\n<p>En Espa\u00f1a es f\u00e1cil hacer negocios. El pa\u00eds representa un mercado muy diverso para los bienes y servicios de Reino Unido, y su valor supera los 15 mil millones de libras anuales. La percepci\u00f3n de las empresas brit\u00e1nicas es claramente positiva y a sus hom\u00f3logos espa\u00f1oles les gusta hacer negocios con ellas.</p>\n\n<p>Existen oportunidades en todo el pa\u00eds en sectores como la sanidad y las ciencias de la vida, en educaci\u00f3n y en el sector aeroespacial. El Gobierno espa\u00f1ol ha llevado a cabo una importante reforma del sector p\u00fablico y han surgido oportunidades a trav\u00e9s de contratos de prestaci\u00f3n de servicios.</p>\n\n<p>En Espa\u00f1a se encuentran algunas de mayores las empresas globales, incluyendo cuatro de los mayores grupos de infraestructuras del mundo. Ocho empresas (Santander, Telef\u00f3nica, Repsol, BBVA, Iberdrola, ACS, Gas Natural y Mapfre) se encuentran en la lista Fortune Global 500 de 2012, que recoge las empresas l\u00edderes internacionales por su cifra de ingresos.</p>\n\n<p>Espa\u00f1a es el segundo fabricante de coches m\u00e1s grande de Europa, detr\u00e1s de Alemania. En el sector tur\u00edstico, el pa\u00eds ocupa igualmente el segundo puesto mundial en ingresos, detr\u00e1s de Estados Unidos.</p>\n\n<p>La experiencia de UK Trade &amp; Investment en los sectores industrial y privado, y los enlaces con los principales sectores de la industria, hacen de UKTI el mejor proveedor de asesoramiento empresarial a la empresa.</p>\n\n<p>Contacte con nuestros expertos en asuntos comerciales para m\u00e1s informaci\u00f3n: </p>\n\n<h3 id=\"madrid\">Madrid</h3>\n<p>UK Trade &amp; Investment \nBritish Embassy\nPaseo de la Castellana, 259-D Torre Espacio - 28046 Madrid\nTel: +34 917 146 412  Email: uktimadrid@fco.gov.uk</p>\n\n<h3 id=\"barcelona\">Barcelona</h3>\n<p>UK Trade &amp; Investment \nBritish Consulate-General \nAvda Diagonal, 477-13\u00ba Edificio Torre de Barcelona - 08036 Barcelona\nTel.: +34 93 366 6207  Email: uktibarcelona@fco.gov.uk</p>\n\n<h3 id=\"bilbao\">Bilbao</h3>\n<p>UK Trade &amp; Investment \nBritish Consulate-General \nAlameda de Urquijo, 2-8 - 48008 Bilbao\nTel.: +34 91 334 47 67   Email: british.consulate@fco.gov.uk</p></div>",
        "change_history": [
            {
                "note": "Added translation",
                "public_timestamp": "2013-03-21T13:21:50+00:00"
            }
        ],
        "first_public_at": "2013-03-21T13:20:50+00:00",
        "format_display_type": "case_study",
        "image": {
            "alt_text": "UKTI Spain",
            "caption": "UKTI Spain",
            "url": "https://assets.digital.cabinet-office.gov.uk/government/uploads/system/uploads/image_data/file/7633/s300_foto_UKTI-1.jpg"
        },
        "tags": {
            "browse_pages": [],
            "topics": [],
            "policies": []
        }
    },
    "format": "case_study",
    "links": {
        "available_translations": [
            {
                "api_url": "https://www.gov.uk/api/content/government/case-studies/doing-business-in-spain",
                "base_path": "/government/case-studies/doing-business-in-spain",
                "locale": "en",
                "title": "Doing business in Spain",
                "web_url": "https://www.gov.uk/government/case-studies/doing-business-in-spain"
            },
            {
                "api_url": "https://www.gov.uk/api/content/government/case-studies/doing-business-in-spain.es",
                "base_path": "/government/case-studies/doing-business-in-spain.es",
                "locale": "es",
                "title": "\u00bfQu\u00e9 puede hacer UKTI por t\u00ed?",
                "web_url": "https://www.gov.uk/government/case-studies/doing-business-in-spain.es"
            },
            {
                "api_url": "https://www.gov.uk/api/content/government/case-studies/doing-business-in-spain.ar",
                "base_path": "/government/case-studies/doing-business-in-spain.ar",
                "locale": "ar",
                "title": "البحرين - تحديث دراسة حالة دولة",
                "web_url": "https://www.gov.uk/government/case-studies/doing-business-in-spain.ar"
            }
        ],
        "lead_organisations": [
            {
                "api_url": "https://www.gov.uk/api/content/government/organisations/uk-trade-investment",
                "base_path": "/government/organisations/uk-trade-investment",
                "locale": "en",
                "title": "UK Trade & Investment",
                "web_url": "https://www.gov.uk/government/organisations/uk-trade-investment"
            }
        ],
        "supporting_organisations": [
            {
                "api_url": "https://www.gov.uk/api/content/government/organisations/foreign-commonwealth-office",
                "base_path": "/government/organisations/foreign-commonwealth-office",
                "locale": "en",
                "title": "Foreign & Commonwealth Office",
                "web_url": "https://www.gov.uk/government/organisations/foreign-commonwealth-office"
            }
        ],
        "world_locations": [
            {
                "api_url": "https://www.gov.uk/api/content/government/world/spain.es",
                "base_path": "/government/world/spain.es",
                "locale": "es",
                "title": "Espa\u00f1a",
                "web_url": "https://www.gov.uk/government/world/spain.es"
            }
        ],
        "worldwide_organisations": []
    },
    "locale": "es",
    "need_ids": [],
    "public_updated_at": "2013-03-21T13:21:50.000+00:00",
    "title": "\u00bfQu\u00e9 puede hacer UKTI por t\u00ed?",
    "updated_at": "2014-12-02T14:59:55.613Z"
}
