=== alphagov/govuk-content-schemas/dist/formats/manual/publisher/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "format",
    "publishing_app",
    "rendering_app",
    "update_type",
    "locale",
    "routes",
    "public_updated_at"
  ],
  "properties": {
    "base_path": {
      "$ref": "#/definitions/absolute_path"
    },
    "content_id": {
      "$ref": "#/definitions/guid"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "format": {
      "type": "string",
      "enum": [
        "manual"
      ]
    },
    "public_updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "publishing_app": {
      "type": "string"
    },
    "rendering_app": {
      "type": "string"
    },
    "update_type": {
      "enum": [
        "major",
        "minor",
        "republish"
      ]
    },
    "locale": {
      "type": "string"
    },
    "need_ids": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "routes": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/route"
      }
    },
    "redirects": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/route"
      }
    },
    "access_limited": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "users"
      ],
      "properties": {
        "users": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "analytics_identifier": {
      "type": "string"
    },
    "phase": {
      "type": "string",
      "enum": [
        "alpha",
        "beta"
      ]
    },
    "details": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "body"
      ],
      "properties": {
        "body": {
          "type": "string"
        },
        "child_section_groups": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "title",
              "child_sections"
            ],
            "properties": {
              "title": {
                "type": "string"
              },
              "child_sections": {
                "type": "array",
                "items": {
                  "required": [
                    "title",
                    "description",
                    "base_path"
                  ],
                  "additionalProperties": false,
                  "type": "object",
                  "properties": {
                    "title": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "base_path": {
                      "$ref": "#/definitions/absolute_path"
                    }
                  }
                }
              }
            }
          }
        },
        "change_notes": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "base_path",
              "title",
              "change_note",
              "published_at"
            ],
            "properties": {
              "base_path": {
                "$ref": "#/definitions/absolute_path"
              },
              "title": {
                "type": "string"
              },
              "change_note": {
                "type": "string"
              },
              "published_at": {
                "type": "string",
                "format": "date-time"
              }
            }
          }
        },
        "organisations": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "title",
              "abbreviation",
              "web_url"
            ],
            "properties": {
              "title": {
                "type": "string"
              },
              "abbreviation": {
                "type": "string"
              },
              "web_url": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "links": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "mainstream_browse_pages": {
          "description": "Powers the /browse section of the site. These are known as sections in some legacy apps.",
          "$ref": "#/definitions/guid_list"
        },
        "topics": {
          "description": "Powers the /topic section of the site. These are known as specialist sectors in some legacy apps.",
          "$ref": "#/definitions/guid_list"
        },
        "policies": {
          "description": "These are for collecting content related to a particular government policy.",
          "$ref": "#/definitions/guid_list"
        },
        "policy_areas": {
          "description": "A largely deprecated tag currently only used to power email alerts.",
          "$ref": "#/definitions/guid_list"
        }
      }
    }
  },
  "definitions": {
    "absolute_path": {
      "type": "string",
      "pattern": "^/(([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})+(/([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)*)?$",
      "description": "A path only. Query string and/or fragment are not allowed."
    },
    "guid": {
      "type": "string",
      "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
    },
    "guid_list": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/guid"
      }
    },
    "route": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "path",
        "type"
      ],
      "properties": {
        "path": {
          "type": "string"
        },
        "type": {
          "enum": [
            "prefix",
            "exact"
          ]
        }
      }
    }
  }
}

=== alphagov/govuk-content-schemas/formats/manual/publisher/examples/manual.json
{
  "content_id": "9b2e22e1-a222-4cda-9799-de7ce56088b0",
  "base_path": "/guidance/content-design",
  "title": "Content design: planning, writing and managing content",
  "description": "Planning and managing digital content to meet the needs the public has of government.",
  "format": "manual",
  "need_ids": [],
  "locale": "en",
  "public_updated_at": "2015-04-27T12:54:27.000+00:00",
  "publishing_app": "specialist-publisher",
  "rendering_app": "manuals-frontend",
  "update_type": "major",
  "details": {
    "body": "\n",
    "child_section_groups": [
      {
        "title": "Contents",
        "child_sections": [
          {
            "title": "What is content design?",
            "description": "Introduction to content design.",
            "base_path": "/guidance/content-design/what-is-content-design"
          },
          {
            "title": "User needs",
            "description": "How to write and record a user need for GOV.UK.",
            "base_path": "/guidance/content-design/user-needs"
          },
          {
            "title": "Planning content",
            "description": "Find out how to decide if something is suitable for GOV.UK, what the content lifecycle is and why accessibility must be planned for.",
            "base_path": "/guidance/content-design/planning-content"
          }
        ]
      }
    ],
    "change_notes": [
      {
        "base_path": "/guidance/content-design/what-is-content-design",
        "title": "What is content design?",
        "change_note": "New section added.",
        "published_at": "2014-10-06T19:49:25Z"
      },
      {
        "base_path": "/guidance/content-design/user-needs",
        "title": "User needs",
        "change_note": "New section added.",
        "published_at": "2014-10-06T19:49:25Z"
      },
      {
        "base_path": "/guidance/content-design/planning-content",
        "title": "Planning content",
        "change_note": "New section added.",
        "published_at": "2014-10-06T19:49:25Z"
      },
      {
        "base_path": "/guidance/content-design/content-types",
        "title": "Content types",
        "change_note": "New section added.",
        "published_at": "2014-10-06T19:49:25Z"
      }
    ],
    "organisations": [
      {
        "title": "Government Digital Service",
        "abbreviation": "GDS",
        "web_url": "https://www.gov.uk/government/organisations/government-digital-service"
      }
    ]
  },
  "routes": [
    {
      "path": "/guidance/content-design",
      "type": "exact"
    }
  ]
}
