=== alphagov/govuk-content-schemas/dist/formats/mainstream_browse_page/publisher/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "format",
    "publishing_app",
    "rendering_app",
    "update_type",
    "locale",
    "public_updated_at"
  ],
  "properties": {
    "base_path": {
      "type": "string"
    },
    "content_id": {
      "type": "string",
      "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "format": {
      "type": "string",
      "enum": [
        "mainstream_browse_page"
      ]
    },
    "public_updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "publishing_app": {
      "type": "string"
    },
    "rendering_app": {
      "type": "string"
    },
    "update_type": {
      "enum": [
        "major",
        "minor",
        "republish"
      ]
    },
    "locale": {
      "type": "string"
    },
    "need_ids": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "routes": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/route"
      }
    },
    "redirects": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/route"
      }
    },
    "access_limited": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "users"
      ],
      "properties": {
        "users": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "details": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "groups": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "name",
              "contents"
            ],
            "properties": {
              "name": {
                "type": "string"
              },
              "contents": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "links": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "top_level_browse_pages": {
          "description": "All top-level browse pages",
          "$ref": "#/definitions/guid_list"
        },
        "active_top_level_browse_page": {
          "description": "The top-level browse page which is active",
          "$ref": "#/definitions/at_most_one_guid_list"
        },
        "second_level_browse_pages": {
          "description": "All 2nd level browse pages under active_top_level_browse_page",
          "$ref": "#/definitions/guid_list"
        },
        "related_topics": {
          "$ref": "#/definitions/guid_list"
        }
      }
    }
  },
  "definitions": {
    "route": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "path",
        "type"
      ],
      "properties": {
        "path": {
          "type": "string"
        },
        "type": {
          "enum": [
            "prefix",
            "exact"
          ]
        }
      }
    },
    "guid_list": {
      "type": "array",
      "items": {
        "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
      }
    },
    "at_most_one_guid_list": {
      "type": "array",
      "items": {
        "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
      },
      "maxItems": 1
    }
  }
}

=== alphagov/govuk-content-schemas/formats/mainstream_browse_page/publisher/examples/mainstream_browse_page_links.json
{
  "content_id": "19ed8498-37ed-4c8e-b0bf-accbb2cf5477",
  "base_path": "/browse",
  "format": "mainstream_browse_page",
  "locale": "en",
  "public_updated_at": "2015-04-20T15:46:10.000+00:00",
  "publishing_app": "collections-publisher",
  "rendering_app": "collections",
  "update_type": "major",
  "links": {
    "top_level_browse_pages": [
      "3c0557d1-518e-4a9b-8920-78524944a28c",
      "94ecd143-c60f-4981-a914-242d0c3b0bd1",
      "88c8dabd-ff05-4530-99ff-ecf3294a9949"
    ]
  },
  "routes": [
    {
      "path": "/browse",
      "type": "exact"
    }
  ]
}

=== alphagov/govuk-content-schemas/formats/mainstream_browse_page/publisher/examples/mainstream_browse_page.json
{
  "content_id": "19ed8498-37ed-4c8e-b0bf-accbb2cf5477",
  "base_path": "/browse",
  "description": "Almost everything on GOV.UK.",
  "details": {},
  "format": "mainstream_browse_page",
  "locale": "en",
  "need_ids": [],
  "public_updated_at": "2015-04-20T15:46:10.000+00:00",
  "publishing_app": "collections-publisher",
  "rendering_app": "collections",
  "update_type": "major",
  "title": "Browse",
  "routes": [
    {
      "path": "/browse",
      "type": "exact"
    }
  ]

}
