=== alphagov/govuk-content-schemas/dist/formats/topic/publisher/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "format",
    "publishing_app",
    "rendering_app",
    "locale",
    "routes",
    "public_updated_at",
    "content_id",
    "update_type"
  ],
  "properties": {
    "base_path": {
      "$ref": "#/definitions/absolute_path"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "format": {
      "type": "string",
      "enum": [
        "topic"
      ]
    },
    "public_updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "publishing_app": {
      "type": "string"
    },
    "rendering_app": {
      "type": "string"
    },
    "locale": {
      "type": "string"
    },
    "need_ids": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "routes": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/route"
      }
    },
    "redirects": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/redirect_route"
      }
    },
    "access_limited": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "users"
      ],
      "properties": {
        "users": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "analytics_identifier": {
      "$ref": "#/definitions/analytics_identifier"
    },
    "phase": {
      "description": "The service design phase of this content item - https://www.gov.uk/service-manual/phases",
      "type": "string",
      "enum": [
        "alpha",
        "beta",
        "live"
      ]
    },
    "content_id": {
      "$ref": "#/definitions/guid"
    },
    "update_type": {
      "enum": [
        "major",
        "minor",
        "republish"
      ]
    },
    "details": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "internal_name": {
          "type": "string",
          "description": "An internal name for admin interfaces. Includes parent."
        },
        "beta": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "groups": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "name",
              "contents"
            ],
            "properties": {
              "name": {
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "contents": {
                "type": "array",
                "items": {
                  "$ref": "#/definitions/absolute_path"
                }
              },
              "content_ids": {
                "$ref": "#/definitions/guid_list"
              }
            }
          }
        }
      }
    },
    "links": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "children": {
          "description": "Any child topics",
          "$ref": "#/definitions/guid_list"
        },
        "linked_items": {
          "description": "Includes all content ids referenced in 'details'. This is a temporary measure to expand content ids for frontends which is planned to be replaced by a dependency resolution service.",
          "$ref": "#/definitions/guid_list"
        },
        "alpha_taxons": {
          "description": "Prototype-stage taxonomy label for this content item",
          "$ref": "#/definitions/guid_list"
        },
        "mainstream_browse_pages": {
          "description": "Powers the /browse section of the site. These are known as sections in some legacy apps.",
          "$ref": "#/definitions/guid_list"
        },
        "topics": {
          "description": "Powers the /topic section of the site. These are known as specialist sectors in some legacy apps.",
          "$ref": "#/definitions/guid_list"
        },
        "organisations": {
          "$ref": "#/definitions/guid_list"
        },
        "parent": {
          "description": "The parent content item.",
          "oneOf": [
            {
              "$ref": "#/definitions/guid_list"
            },
            {
              "$ref": "#/definitions/parent"
            }
          ],
          "maxItems": 1
        },
        "policies": {
          "description": "These are for collecting content related to a particular government policy.",
          "$ref": "#/definitions/guid_list"
        },
        "policy_areas": {
          "description": "A largely deprecated tag currently only used to power email alerts.",
          "$ref": "#/definitions/guid_list"
        }
      }
    }
  },
  "definitions": {
    "absolute_path": {
      "type": "string",
      "pattern": "^/(([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})+(/([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)*)?$",
      "description": "A path only. Query string and/or fragment are not allowed."
    },
    "absolute_fullpath": {
      "type": "string",
      "pattern": "^/(([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})+(/([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)*)?(\\?([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)?(#([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)?$",
      "description": "A path with optional query string and/or fragment."
    },
    "analytics_identifier": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "description": "A short identifier we send to Google Analytics for multi-valued fields. This means we avoid the truncated values we would get if we sent the path or slug of eg organisations."
    },
    "guid": {
      "type": "string",
      "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
    },
    "guid_list": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/guid"
      }
    },
    "image": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "url"
      ],
      "properties": {
        "url": {
          "type": "string",
          "format": "uri"
        },
        "alt_text": {
          "type": "string"
        },
        "caption": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        }
      }
    },
    "parent": {
      "type": "object",
      "additionalPropeties": false,
      "required": [
        "title",
        "web_url",
        "parent"
      ],
      "properties": {
        "title": {
          "type": "string"
        },
        "web_url": {
          "type": "string",
          "format": "uri"
        },
        "parent": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/parent"
            }
          ]
        }
      }
    },
    "route": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "path",
        "type"
      ],
      "properties": {
        "path": {
          "type": "string"
        },
        "type": {
          "enum": [
            "prefix",
            "exact"
          ]
        }
      }
    },
    "redirect_route": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "path",
        "type",
        "destination"
      ],
      "properties": {
        "path": {
          "$ref": "#/definitions/absolute_path"
        },
        "type": {
          "enum": [
            "prefix",
            "exact"
          ]
        },
        "destination": {
          "$ref": "#/definitions/absolute_fullpath"
        },
        "segments_mode": {
          "enum": [
            "preserve",
            "ignore"
          ],
          "description": "For prefix redirects, preserve or ignore the rest of the fullpath. For exact, preserve or ignore the querystring."
        }
      }
    },
    "multiple_content_types": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "content_type",
          "content"
        ],
        "properties": {
          "content_type": {
            "type": "string"
          },
          "content": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== alphagov/govuk-content-schemas/formats/topic/publisher/examples/topic_links.json
{
    "content_id": "63d98739-fc60-4e28-a65f-edb56000fd39",
    "base_path": "/topic/oil-and-gas",
    "format": "topic",
    "publishing_app": "collections-publisher",
    "rendering_app": "collections",
    "update_type": "major",
    "links": {
      "children": [
        "f6eef5ca-be55-41b2-98be-f72b3e649b84",
        "0a6116da-fbf6-4d5c-baa9-2a74ae8a8fb9"
      ]
    },
    "routes": [
      {
        "path": "/topic",
        "type": "exact"
      }
    ],
    "locale": "en",
    "public_updated_at": "2015-04-20T15:46:10.000+00:00"
}
