=== alphagov/govuk-content-schemas/dist/formats/service_manual_topic/publisher_v2/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "title",
    "format",
    "publishing_app",
    "rendering_app",
    "locale",
    "routes",
    "public_updated_at",
    "base_path"
  ],
  "properties": {
    "base_path": {
      "$ref": "#/definitions/absolute_path"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "format": {
      "type": "string",
      "enum": [
        "service_manual_topic"
      ]
    },
    "public_updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "publishing_app": {
      "type": "string"
    },
    "rendering_app": {
      "type": "string"
    },
    "locale": {
      "type": "string"
    },
    "need_ids": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "routes": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/route"
      }
    },
    "redirects": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/redirect_route"
      }
    },
    "access_limited": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "users"
      ],
      "properties": {
        "users": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "analytics_identifier": {
      "$ref": "#/definitions/analytics_identifier"
    },
    "phase": {
      "description": "The service design phase of this content item - https://www.gov.uk/service-manual/phases",
      "type": "string",
      "enum": [
        "alpha",
        "beta",
        "live"
      ]
    },
    "previous_version": {
      "type": "string"
    },
    "update_type": {
      "enum": [
        "major",
        "minor",
        "republish"
      ]
    },
    "details": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "groups": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "name",
              "contents"
            ],
            "properties": {
              "name": {
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "contents": {
                "type": "array",
                "items": {
                  "$ref": "#/definitions/absolute_path"
                }
              },
              "content_ids": {
                "$ref": "#/definitions/guid_list"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "absolute_path": {
      "type": "string",
      "pattern": "^/(([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})+(/([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)*)?$",
      "description": "A path only. Query string and/or fragment are not allowed."
    },
    "absolute_fullpath": {
      "type": "string",
      "pattern": "^/(([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})+(/([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)*)?(\\?([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)?(#([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)?$",
      "description": "A path with optional query string and/or fragment."
    },
    "analytics_identifier": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "description": "A short identifier we send to Google Analytics for multi-valued fields. This means we avoid the truncated values we would get if we sent the path or slug of eg organisations."
    },
    "guid": {
      "type": "string",
      "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
    },
    "guid_list": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/guid"
      }
    },
    "image": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "url"
      ],
      "properties": {
        "url": {
          "type": "string",
          "format": "uri"
        },
        "alt_text": {
          "type": "string"
        },
        "caption": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        }
      }
    },
    "route": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "path",
        "type"
      ],
      "properties": {
        "path": {
          "type": "string"
        },
        "type": {
          "enum": [
            "prefix",
            "exact"
          ]
        }
      }
    },
    "redirect_route": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "path",
        "type",
        "destination"
      ],
      "properties": {
        "path": {
          "$ref": "#/definitions/absolute_path"
        },
        "type": {
          "enum": [
            "prefix",
            "exact"
          ]
        },
        "destination": {
          "$ref": "#/definitions/absolute_fullpath"
        },
        "segments_mode": {
          "enum": [
            "preserve",
            "ignore"
          ],
          "description": "For prefix redirects, preserve or ignore the rest of the fullpath. For exact, preserve or ignore the querystring."
        }
      }
    },
    "multiple_content_types": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "content_type",
          "content"
        ],
        "properties": {
          "content_type": {
            "type": "string"
          },
          "content": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== alphagov/govuk-content-schemas/formats/service_manual_topic/publisher_v2/examples/service_manual_topic.json
{
  "publishing_app":"service-manual-publisher",
  "rendering_app":"government-frontend",
  "format":"service_manual_topic",
  "locale":"en",
  "base_path":"/service-manual/technology",
  "public_updated_at":"2016-02-11T15:42:55Z",
  "title":"Technology",
  "description":"A tech description.",
  "phase":"beta",
  "routes": [
    {
      "type":"exact",
      "path":"/service-manual/technology"
    }
  ],
  "details": {
    "groups": [
      {
        "name":"Security",
        "description":"A security description.",
        "contents": [
          "/service-manual/operations/cloud-security",
          "/service-manual/domain-names/https"
        ],
        "content_ids": [
          "f84918f1-de82-4a8e-a4c5-d65872307a4f",
          "1e8c2361-ad63-4513-b7c0-9888c0880092"
        ]
      }
    ]
  }
}
