=== alphagov/govuk-content-schemas/dist/formats/email_alert_signup/frontend/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "base_path",
    "format",
    "locale",
    "public_updated_at"
  ],
  "properties": {
    "base_path": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "format": {
      "type": "string",
      "enum": [
        "email_alert_signup"
      ]
    },
    "public_updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "locale": {
      "type": "string"
    },
    "need_ids": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "details": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "summary",
        "tags",
        "format_type"
      ],
      "properties": {
        "summary": {
          "type": "string"
        },
        "tags": {
          "type": "object"
        },
        "breadcrumbs": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "link",
              "title"
            ],
            "properties": {
              "link": {
                "type": "string",
                "format": "uri"
              },
              "title": {
                "type": "string"
              }
            }
          }
        },
        "format_type": {
          "type": "string"
        }
      }
    },
    "links": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "available_translations": {
          "$ref": "#/definitions/frontend_links"
        }
      }
    },
    "updated_at": {
      "type": "string",
      "format": "date-time"
    }
  },
  "definitions": {
    "route": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "path",
        "type"
      ],
      "properties": {
        "path": {
          "type": "string"
        },
        "type": {
          "enum": [
            "prefix",
            "exact"
          ]
        }
      }
    },
    "guid_list": {
      "type": "array",
      "items": {
        "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
      }
    },
    "frontend_links": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "title": {
            "type": "string"
          },
          "base_path": {
            "type": "string"
          },
          "api_url": {
            "type": "string",
            "format": "uri"
          },
          "web_url": {
            "type": "string",
            "format": "uri"
          },
          "locale": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== alphagov/govuk-content-schemas/formats/email_alert_signup/frontend/examples/email_alert_signup.json
{
  "base_path": "/government/policies/employment/email-signup",
  "title": "Employment",
  "description": "",
  "format": "email_alert_signup",
  "need_ids": [],
  "locale": "en",
  "updated_at": "2015-04-14T13:11:45.809Z",
  "public_updated_at": "2015-04-14T10:56:00.000+00:00",
  "details": {
    "breadcrumbs": [
      {
        "title": "Employment",
        "link": "https://www.gov.uk/government/policies/employment"
      }
    ],
    "summary": "You'll get an email each time any information on this policy is published or updated.",
    "tags": {
      "policy": [
        "employment"
      ]
    },
    "format_type": "policy"
  },
  "links": {}
}
