=== alphagov/govuk-content-schemas/dist/formats/policy/publisher/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "format",
    "publishing_app",
    "rendering_app",
    "update_type",
    "locale",
    "routes",
    "public_updated_at"
  ],
  "properties": {
    "base_path": {
      "$ref": "#/definitions/absolute_path"
    },
    "content_id": {
      "$ref": "#/definitions/guid"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "format": {
      "type": "string",
      "enum": [
        "policy"
      ]
    },
    "public_updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "publishing_app": {
      "type": "string"
    },
    "rendering_app": {
      "type": "string"
    },
    "update_type": {
      "enum": [
        "major",
        "minor",
        "republish"
      ]
    },
    "locale": {
      "type": "string"
    },
    "need_ids": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "routes": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/route"
      }
    },
    "redirects": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/route"
      }
    },
    "access_limited": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "users"
      ],
      "properties": {
        "users": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "analytics_identifier": {
      "type": "string"
    },
    "phase": {
      "description": "The service design phase of this content item - https://www.gov.uk/service-manual/phases",
      "type": "string",
      "enum": [
        "alpha",
        "beta",
        "live"
      ]
    },
    "details": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "document_noun",
        "facets"
      ],
      "properties": {
        "document_noun": {
          "type": "string"
        },
        "default_documents_per_page": {
          "type": "integer"
        },
        "email_signup_enabled": {
          "type": "boolean"
        },
        "default_order": {
          "type": "string"
        },
        "filter": {
          "type": "object",
          "additionalProperties": true
        },
        "facets": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": true,
            "required": [
              "key",
              "filterable",
              "display_as_result_metadata"
            ],
            "properties": {
              "key": {
                "type": "string"
              },
              "filterable": {
                "type": "boolean"
              },
              "display_as_result_metadata": {
                "type": "boolean"
              },
              "name": {
                "type": "string"
              },
              "type": {
                "type": "string"
              },
              "allowed_values": {
                "type": "array",
                "items": {
                  "type": "object",
                  "additionalProperties": false,
                  "required": [
                    "label",
                    "value"
                  ],
                  "properties": {
                    "label": {
                      "type": "string"
                    },
                    "value": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        },
        "human_readable_finder_format": {
          "type": "string"
        },
        "show_summaries": {
          "type": "boolean"
        },
        "signup_link": {
          "type": "string"
        },
        "summary": {
          "type": "string"
        },
        "nation_applicability": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "applies_to",
            "alternative_policies"
          ],
          "properties": {
            "applies_to": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "alternative_policies": {
              "type": "array",
              "items": {
                "type": "object",
                "required": [
                  "nation",
                  "alt_policy_url"
                ],
                "properties": {
                  "nation": {
                    "type": "string"
                  },
                  "alt_policy_url": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    },
    "links": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "organisations",
        "related"
      ],
      "properties": {
        "people": {
          "$ref": "#/definitions/guid_list"
        },
        "working_groups": {
          "$ref": "#/definitions/guid_list"
        },
        "related": {
          "$ref": "#/definitions/guid_list"
        },
        "email_alert_signup": {
          "$ref": "#/definitions/guid_list"
        },
        "available_translations": {
          "$ref": "#/definitions/guid_list"
        },
        "mainstream_browse_pages": {
          "description": "Powers the /browse section of the site. These are known as sections in some legacy apps.",
          "$ref": "#/definitions/guid_list"
        },
        "topics": {
          "description": "Powers the /topic section of the site. These are known as specialist sectors in some legacy apps.",
          "$ref": "#/definitions/guid_list"
        },
        "organisations": {
          "$ref": "#/definitions/guid_list"
        },
        "policies": {
          "description": "These are for collecting content related to a particular government policy.",
          "$ref": "#/definitions/guid_list"
        },
        "policy_areas": {
          "description": "A largely deprecated tag currently only used to power email alerts.",
          "$ref": "#/definitions/guid_list"
        }
      }
    }
  },
  "definitions": {
    "absolute_path": {
      "type": "string",
      "pattern": "^/(([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})+(/([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)*)?$",
      "description": "A path only. Query string and/or fragment are not allowed."
    },
    "guid": {
      "type": "string",
      "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
    },
    "guid_list": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/guid"
      }
    },
    "route": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "path",
        "type"
      ],
      "properties": {
        "path": {
          "type": "string"
        },
        "type": {
          "enum": [
            "prefix",
            "exact"
          ]
        }
      }
    }
  }
}

=== alphagov/govuk-content-schemas/formats/policy/publisher/examples/policy.json
{
  "content_id": "f8c3682c-3a88-4f35-afba-3607384e39e6",
  "base_path": "/government/policies/benefits-reform",
  "title": "Benefits Reform",
  "description": "",
  "format": "policy",
  "need_ids": [],
  "locale": "en",
  "public_updated_at": "2015-03-10T11:55:11.066+00:00",
  "publishing_app": "whitehall",
  "rendering_app": "government-frontend",
  "update_type": "minor",
  "details": {
    "document_noun": "document",
    "default_documents_per_page": 10,
    "email_signup_enabled": false,
    "filter": {
      "policies": [
        "benefits-reform"
      ]
    },
    "human_readable_finder_format": "Policy",
    "signup_link": "",
    "summary": "The government believes that the current benefits system is too complex, and there are insufficient incentives to encourage people on benefits to start paid work or increase their hours.",
    "show_summaries": false,
    "facets": [
      {
        "key": "is_historic",
        "display_as_result_metadata": true,
        "filterable": false
      },
      {
        "key": "government_name",
        "display_as_result_metadata": true,
        "filterable": false
      },
      {
        "key": "public_timestamp",
        "name": "Published",
        "short_name": "Updated",
        "type": "date",
        "display_as_result_metadata": true,
        "filterable": true
      },
      {
        "key": "organisations",
        "short_name": "From",
        "type": "text",
        "display_as_result_metadata": true,
        "filterable": false
      },
      {
        "key": "display_type",
        "short_name": "Type",
        "type": "text",
        "display_as_result_metadata": true,
        "filterable": false
      }
   ]
 },
 "routes": [
   {
     "path": "/government/policies/benefits-reform",
     "type": "exact"
   }
 ]
}

=== alphagov/govuk-content-schemas/formats/policy/publisher/examples/policy_links.json
{
  "content_id": "f8c3682c-3a88-4f35-afba-3607384e39e6",
  "base_path": "/government/policies/benefits-reform",
  "format": "policy",
  "locale": "en",
  "public_updated_at": "2015-03-10T11:55:11.066+00:00",
  "publishing_app": "whitehall",
  "rendering_app": "government-frontend",
  "update_type": "minor",
  "links": {
    "organisations":[
      "a4759607-4fd8-4cf0-9d56-af9d14a71162"
    ],
    "people": [],
    "working_groups": [],
    "related":[],
    "email_alert_signup":[
      "69938c64-4bb3-4b4f-814b-e73cb71831ef"
    ]
  },
  "routes": [
    {
      "path": "/government/policies/benefits-reform",
      "type": "exact"
    }
  ]
}
