=== alphagov/govuk-content-schemas/dist/formats/special_route/publisher/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "format",
    "publishing_app",
    "update_type",
    "routes"
  ],
  "properties": {
    "base_path": {
      "$ref": "#/definitions/absolute_path"
    },
    "content_id": {
      "type": "string",
      "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
    },
    "format": {
      "enum": [
        "special_route"
      ]
    },
    "publishing_app": {
      "type": "string"
    },
    "rendering_app": {
      "type": "string"
    },
    "update_type": {
      "enum": [
        "major",
        "minor",
        "republish"
      ]
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "public_updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "routes": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/route"
      }
    }
  },
  "definitions": {
    "absolute_path": {
      "type": "string",
      "pattern": "^/(([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})+(/([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)*)?$",
      "description": "A path only. Query string and/or fragment are not allowed."
    },
    "guid": {
      "type": "string",
      "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
    },
    "route": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "path",
        "type"
      ],
      "properties": {
        "path": {
          "type": "string"
        },
        "type": {
          "enum": [
            "prefix",
            "exact"
          ]
        }
      }
    }
  }
}

=== alphagov/govuk-content-schemas/formats/special_route/publisher_v2/robots.txt.json
{
  "base_path": "/robots.txt",
  "content_id": "a5d86183-7252-4426-aad2-3f732f7f2581",
  "title": "Instructions for crawler robots",
  "description": "robots.txt provides rules for which parts of GOV.UK are permitted to be crawled by different bots.",
  "format": "special_route",
  "public_updated_at": "2015-07-30T13:58:11+00:00",
  "publishing_app": "static",
  "rendering_app": "static",
  "routes": [
    {
      "path": "/robots.txt",
      "type": "exact"
    }
  ],
  "update_type": "major"
}
