=== alphagov/govuk-content-schemas/dist/formats/travel_advice/publisher/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "format",
    "publishing_app",
    "rendering_app",
    "locale",
    "routes",
    "public_updated_at",
    "content_id",
    "update_type"
  ],
  "properties": {
    "base_path": {
      "$ref": "#/definitions/absolute_path"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "format": {
      "type": "string",
      "enum": [
        "travel_advice"
      ]
    },
    "public_updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "publishing_app": {
      "type": "string"
    },
    "rendering_app": {
      "type": "string"
    },
    "locale": {
      "type": "string"
    },
    "need_ids": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "routes": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/route"
      }
    },
    "redirects": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/redirect_route"
      }
    },
    "access_limited": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "users"
      ],
      "properties": {
        "users": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "analytics_identifier": {
      "$ref": "#/definitions/analytics_identifier"
    },
    "phase": {
      "description": "The service design phase of this content item - https://www.gov.uk/service-manual/phases",
      "type": "string",
      "enum": [
        "alpha",
        "beta",
        "live"
      ]
    },
    "content_id": {
      "$ref": "#/definitions/guid"
    },
    "update_type": {
      "enum": [
        "major",
        "minor",
        "republish"
      ]
    },
    "details": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "summary",
        "country",
        "updated_at",
        "reviewed_at",
        "change_description",
        "alert_status",
        "email_signup_link",
        "parts"
      ],
      "properties": {
        "summary": {
          "$ref": "#/definitions/multiple_content_types"
        },
        "country": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "slug",
            "name"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "slug": {
              "type": "string"
            }
          }
        },
        "updated_at": {
          "type": "string",
          "format": "date-time"
        },
        "reviewed_at": {
          "type": "string",
          "format": "date-time"
        },
        "change_description": {
          "type": "string"
        },
        "alert_status": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "email_signup_link": {
          "type": "string",
          "format": "uri"
        },
        "image": {
          "$ref": "#/definitions/asset_link"
        },
        "document": {
          "$ref": "#/definitions/asset_link"
        },
        "parts": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "slug",
              "title",
              "body"
            ],
            "properties": {
              "slug": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "body": {
                "$ref": "#/definitions/multiple_content_types"
              }
            }
          }
        }
      }
    },
    "links": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "related": {
          "$ref": "#/definitions/guid_list"
        },
        "alpha_taxons": {
          "description": "Prototype-stage taxonomy label for this content item",
          "$ref": "#/definitions/guid_list"
        },
        "mainstream_browse_pages": {
          "description": "Powers the /browse section of the site. These are known as sections in some legacy apps.",
          "$ref": "#/definitions/guid_list"
        },
        "topics": {
          "description": "Powers the /topic section of the site. These are known as specialist sectors in some legacy apps.",
          "$ref": "#/definitions/guid_list"
        },
        "organisations": {
          "$ref": "#/definitions/guid_list"
        },
        "parent": {
          "description": "The parent content item.",
          "$ref": "#/definitions/guid_list",
          "maxItems": 1
        },
        "policies": {
          "description": "These are for collecting content related to a particular government policy.",
          "$ref": "#/definitions/guid_list"
        },
        "policy_areas": {
          "description": "A largely deprecated tag currently only used to power email alerts.",
          "$ref": "#/definitions/guid_list"
        }
      }
    }
  },
  "definitions": {
    "absolute_path": {
      "type": "string",
      "pattern": "^/(([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})+(/([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)*)?$",
      "description": "A path only. Query string and/or fragment are not allowed."
    },
    "absolute_fullpath": {
      "type": "string",
      "pattern": "^/(([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})+(/([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)*)?(\\?([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)?(#([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)?$",
      "description": "A path with optional query string and/or fragment."
    },
    "analytics_identifier": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "description": "A short identifier we send to Google Analytics for multi-valued fields. This means we avoid the truncated values we would get if we sent the path or slug of eg organisations."
    },
    "guid": {
      "type": "string",
      "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
    },
    "guid_list": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/guid"
      }
    },
    "image": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "url"
      ],
      "properties": {
        "url": {
          "type": "string",
          "format": "uri"
        },
        "alt_text": {
          "type": "string"
        },
        "caption": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        }
      }
    },
    "route": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "path",
        "type"
      ],
      "properties": {
        "path": {
          "type": "string"
        },
        "type": {
          "enum": [
            "prefix",
            "exact"
          ]
        }
      }
    },
    "redirect_route": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "path",
        "type",
        "destination"
      ],
      "properties": {
        "path": {
          "$ref": "#/definitions/absolute_path"
        },
        "type": {
          "enum": [
            "prefix",
            "exact"
          ]
        },
        "destination": {
          "$ref": "#/definitions/absolute_fullpath"
        },
        "segments_mode": {
          "enum": [
            "preserve",
            "ignore"
          ],
          "description": "For prefix redirects, preserve or ignore the rest of the fullpath. For exact, preserve or ignore the querystring."
        }
      }
    },
    "multiple_content_types": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "content_type",
          "content"
        ],
        "properties": {
          "content_type": {
            "type": "string"
          },
          "content": {
            "type": "string"
          }
        }
      }
    },
    "asset_link": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "url",
        "content_type"
      ],
      "properties": {
        "url": {
          "type": "string",
          "format": "uri"
        },
        "content_type": {
          "type": "string"
        }
      }
    }
  }
}

=== alphagov/govuk-content-schemas/formats/travel_advice/publisher/examples/travel_advice_links.json
{
  "content_id": "2a3938e1-d588-45fc-8c8f-0f51814d5409",
  "base_path": "/foreign-travel-advice/albania",
  "format": "travel_advice",
  "links": {
    "mainstream_browse_pages": [
      "b9849cd6-61a7-42dc-8124-362d2c7d48b0",
      "bbb8985a-5451-4e9d-a601-8c55853a096c"
    ],
    "organisations": [
      "8b19c238-54e3-4e27-b0d7-60f8e2a677c9"
    ],
    "related": [
      "95f9c380-30bc-44c7-86b4-e9c9ef0fc272",
      "e4d06cb9-9e2e-4e82-b802-0aad013ae16c"
    ]
  },
  "locale": "en",
  "need_ids": ["101191"],
  "public_updated_at": "2015-10-15T11:00:20+01:00",
  "publishing_app": "travel-advice-publisher",
  "rendering_app": "frontend",
  "update_type": "major",
  "routes": [
    {
      "path": "/foreign-travel-advice/albania",
      "type": "exact"
    }
  ]
}
