=== alphagov/govuk-content-schemas/formats/finder/publisher/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "format",
    "publishing_app",
    "rendering_app",
    "update_type",
    "locale"
  ],
  "properties": {
    "base_path": {
      "type": "string"
    },
    "content_id": {
      "type": "string",
      "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "format": {
      "type": "string",
      "enum": [
        "finder"
      ]
    },
    "public_updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "publishing_app": {
      "type": "string"
    },
    "rendering_app": {
      "type": "string"
    },
    "update_type": {
      "enum": [
        "major",
        "minor",
        "republish"
      ]
    },
    "locale": {
      "type": "string"
    },
    "need_ids": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "routes": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/route"
      }
    },
    "redirects": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/route"
      }
    },
    "details": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "document_noun",
        "filter",
        "facets"
      ],
      "properties": {
        "beta": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "beta_message": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "document_noun": {
          "type": "string",
          "additionalProperties": false
        },
        "email_signup_enabled": {
          "type": "boolean"
        },
        "filter": {
          "description": "This is the fixed filter that scopes the finder",
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "document_type": {
              "type": "string"
            },
            "organisations": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "facets": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "key",
              "filterable",
              "display_as_result_metadata"
            ],
            "properties": {
              "key": {
                "type": "string"
              },
              "filterable": {
                "type": "boolean"
              },
              "display_as_result_metadata": {
                "type": "boolean"
              },
              "name": {
                "type": "string"
              },
              "preposition": {
                "type": "string"
              },
              "short_name": {
                "type": "string"
              },
              "type": {
                "type": "string"
              },
              "allowed_values": {
                "type": "array",
                "items": {
                  "type": "object",
                  "additionalProperties": false,
                  "required": [
                    "label",
                    "value"
                  ],
                  "properties": {
                    "label": {
                      "type": "string"
                    },
                    "value": {
                      "type": "string"
                    }
                  }
                }
              },
              "result_metadata_name_key": {
                "type": "string"
              }
            }
          }
        },
        "format_name": {
          "type": "string"
        },
        "show_summaries": {
          "type": "boolean"
        },
        "signup_link": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "summary": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        }
      }
    },
    "links": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "organisations": {
          "$ref": "#/definitions/guid_list"
        },
        "related": {
          "$ref": "#/definitions/guid_list"
        },
        "email_alert_signup": {
          "$ref": "#/definitions/guid_list"
        },
        "available_translations": {
          "$ref": "#/definitions/guid_list"
        }
      }
    }
  },
  "definitions": {
    "route": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "path",
        "type"
      ],
      "properties": {
        "path": {
          "type": "string"
        },
        "type": {
          "enum": [
            "prefix",
            "exact"
          ]
        }
      }
    },
    "guid_list": {
      "type": "array",
      "items": {
        "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
      }
    }
  }
}

=== alphagov/govuk-content-schemas/formats/finder/publisher/examples/finder_links.json
{
  "content_id": "3631309f-b9c0-4942-afe6-3ae3819fc6a1",
  "base_path": "/cma-cases",
  "format": "finder",
  "locale": "en",
  "public_updated_at": "2015-04-30T10:41:26.000+00:00",
  "publishing_app": "specialist-publisher",
  "rendering_app": "finder-frontend",
  "update_type": "major",
  "links": {
    "organisations": [
      "3338f283-64a1-4062-842e-677f520c1f15"
    ],
    "related": [],
    "email_alert_signup": [
      "5c35b119-aebc-4ec8-9413-370bd01c24b3"
    ]
  },
  "routes": [
    {
      "path": "/cma-cases",
      "type": "exact"
    }
  ]
}
