=== alphagov/govuk-content-schemas/dist/formats/coming_soon/publisher/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "format",
    "publishing_app",
    "rendering_app",
    "update_type",
    "locale",
    "public_updated_at"
  ],
  "properties": {
    "base_path": {
      "type": "string"
    },
    "content_id": {
      "type": "string",
      "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "format": {
      "type": "string",
      "enum": [
        "coming_soon"
      ]
    },
    "public_updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "publishing_app": {
      "type": "string"
    },
    "rendering_app": {
      "type": "string"
    },
    "update_type": {
      "enum": [
        "major",
        "minor",
        "republish"
      ]
    },
    "locale": {
      "type": "string"
    },
    "need_ids": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "routes": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/route"
      }
    },
    "redirects": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/route"
      }
    },
    "access_limited": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "users"
      ],
      "properties": {
        "users": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "details": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "publish_time"
      ],
      "properties": {
        "publish_time": {
          "type": "string",
          "format": "date-time"
        }
      }
    }
  },
  "definitions": {
    "route": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "path",
        "type"
      ],
      "properties": {
        "path": {
          "type": "string"
        },
        "type": {
          "enum": [
            "prefix",
            "exact"
          ]
        }
      }
    }
  }
}

=== alphagov/govuk-content-schemas/formats/coming_soon/publisher/examples/coming_soon.json
{
  "content_id": "3e0467ef-640b-4a9f-8f9c-2b174d9274e6",
  "base_path": "/government/case-studies/a-random-title-for-a-random-document",
  "details": {
    "publish_time": "2014-12-17T09:30:00+00:00"
  },
  "format": "coming_soon",
  "locale": "en",
  "title": "Coming soon",
  "publishing_app": "whitehall",
  "rendering_app": "government-frontend",
  "update_type": "major",
   "routes": [
    {
      "path": "/government/case-studies/a-random-title-for-a-random-document",
      "type": "exact"
    }
  ],
  "public_updated_at": "2014-12-15T12:31:00+00:00"
}
